-- Project gallery: the carousel that sits under the hero on both landing
-- variants. One row per slide, hung off services so it inherits that table's
-- brand + slug identity — landing_v2 keys on a bare slug and could not tell
-- Premium Chimneys' "chimney-sweep" from Premium Air Ducts'.
--
-- The caption belongs here rather than on a media record because it describes
-- the pairing, not the photograph: the same roof-brush shot is "Full flue
-- brush-out from the roof" in the sweep gallery and "Draft tested after
-- installation" in the caps one.
--
-- Read path: getServiceData embeds these rows in the services query
-- (services?select=*,service_gallery(...)), so they cost no extra round trip.

create table if not exists public.service_gallery (
  id              uuid primary key default gen_random_uuid(),
  service_id      uuid not null references public.services(id) on delete cascade,
  sort_order      int  not null,
  image_url       text not null,
  -- 640w sibling for phones. Null where the source was already smaller than
  -- the slot, in which case image_url is served on its own.
  image_url_small text,
  scope           text,          -- chip over the photo, e.g. 'Exterior · Flue'
  title           text not null, -- the h3 under the photo
  result          text,          -- the line beside the green check
  alt             text not null,
  created_at      timestamptz not null default now(),
  unique (service_id, sort_order)
);

create index if not exists service_gallery_service_idx
  on public.service_gallery (service_id, sort_order);

-- Public read, same posture as services / cities / v2_hero_images.
alter table public.service_gallery enable row level security;
drop policy if exists "public read service_gallery" on public.service_gallery;
create policy "public read service_gallery"
  on public.service_gallery for select using (true);

-- ── Seed ──────────────────────────────────────────────────────────────────
-- The set the site shipped with, so the table starts where the page already is.
-- Images live in the public landing-v2 bucket under gallery/, resized to the
-- 460px slot (920w for retina, 640w for phones).
insert into public.service_gallery
  (service_id, sort_order, image_url, image_url_small, scope, title, result, alt)
select s.id, v.sort_order, v.image_url, v.image_url_small, v.scope, v.title, v.result, v.alt
from (values
  ('chimney-sweep', 1, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-sweep-roof-brush-flue-cleaning-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-sweep-roof-brush-flue-cleaning-640.webp', 'Exterior · Flue', 'Full flue brush-out from the roof', 'Creosote removed', 'Technician brushing a chimney flue from the roof'),
  ('chimney-sweep', 2, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-640.webp', 'Interior · Firebox', 'Years of soot cleared out', 'Like new again', 'Masonry firebox before and after a deep clean'),
  ('chimney-sweep', 3, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-inspection-roofline-flue-evaluation-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-inspection-roofline-flue-evaluation-640.webp', 'Exterior · Roofline', 'Flue checked after the brush-out', 'Draft confirmed', 'Chimney flue evaluated at the roofline'),
  ('chimney-sweep', 4, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-in-black-painted-firebox-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-in-black-painted-firebox-640.webp', 'Interior · Log set', 'Logs lifted, firebox vacuumed out', 'No dust indoors', 'Clean gas log set in a black painted firebox'),
  ('chimney-sweep', 5, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-640.webp', 'Interior · Handover', 'Left ready to light', 'Safe to use nightly', 'Painted brick fireplace lit in the evening'),
  ('chimney-inspection', 1, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/crumbling-brick-crown-rebuilt-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/crumbling-brick-crown-rebuilt-before-after-640.webp', 'Exterior · Crown', 'Crumbling crown found at the top', 'Rebuilt and capped', 'Crumbling brick chimney crown before and after being rebuilt'),
  ('chimney-inspection', 2, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chase-siding-trim-and-crown-replaced-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chase-siding-trim-and-crown-replaced-before-after-640.webp', 'Exterior · Chase', 'Open joint traced to the chase trim', 'Sealed and re-clad', 'Chimney chase trim and crown before and after replacement'),
  ('chimney-inspection', 3, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/round-vent-cap-replaced-with-hip-cap-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/round-vent-cap-replaced-with-hip-cap-before-after-640.webp', 'Exterior · Cap', 'Worn cap flagged from the roof', 'Replaced same week', 'Round vent cap before and after replacement with a hip cap'),
  ('chimney-inspection', 4, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/peeling-chase-resided-with-tan-cap-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/peeling-chase-resided-with-tan-cap-before-after-640.webp', 'Exterior · Flashing', 'Rust found where the chase meets roof', 'Watertight again', 'Weathered chimney chase before and after being re-sided'),
  ('chimney-inspection', 5, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/sage-chase-resided-with-black-cap-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/sage-chase-resided-with-black-cap-before-after-640.webp', 'Exterior · Structure', 'Failing paint hiding rotted board', 'Caught before it spread', 'Chimney chase with failing paint before and after re-siding'),
  ('chimney-repair', 1, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/crumbling-brick-crown-rebuilt-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/crumbling-brick-crown-rebuilt-before-after-640.webp', 'Exterior · Crown', 'Crumbling brick crown rebuilt', 'Structurally sound', 'Crumbling brick chimney crown before and after being rebuilt'),
  ('chimney-repair', 2, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chase-siding-trim-and-crown-replaced-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chase-siding-trim-and-crown-replaced-before-after-640.webp', 'Exterior · Chase', 'Chase re-clad, trim and crown replaced', 'Watertight', 'Chimney chase trim and crown before and after replacement'),
  ('chimney-repair', 3, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/peeling-chase-resided-with-tan-cap-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/peeling-chase-resided-with-tan-cap-before-after-640.webp', 'Exterior · Siding', 'Peeling chase stripped and re-sided', 'Whole chase renewed', 'Weathered chimney chase before and after being re-sided'),
  ('chimney-repair', 4, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/sage-chase-resided-with-black-cap-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/sage-chase-resided-with-black-cap-before-after-640.webp', 'Exterior · Structure', 'Rot cut out and the chase rebuilt', 'Solid again', 'Chimney chase with failing paint before and after re-siding'),
  ('chimney-repair', 5, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/round-vent-cap-replaced-with-hip-cap-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/round-vent-cap-replaced-with-hip-cap-before-after-640.webp', 'Exterior · Cap', 'New crown and cap to finish', 'Water kept out', 'Round vent cap before and after replacement with a hip cap'),
  ('chimney-caps', 1, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/two-hip-caps-on-a-metal-roof-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/two-hip-caps-on-a-metal-roof-640.webp', 'Exterior · Multi-flue', 'Matching caps on both flues', 'Sized to each flue', 'Two hip caps installed on chimneys above a metal roof'),
  ('chimney-caps', 2, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/technician-beside-black-hip-cap-tile-roof-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/technician-beside-black-hip-cap-tile-roof-640.webp', 'Exterior · Install', 'Black hip cap set and sealed', 'Fitted on site', 'Technician beside a newly installed black hip cap'),
  ('chimney-caps', 3, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/stucco-chimney-brown-hip-cap-at-sunset-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/stucco-chimney-brown-hip-cap-at-sunset-640.webp', 'Exterior · Finish', 'Cap colour matched to the trim', 'Blends with the roof', 'Stucco chimney with a brown hip cap at sunset'),
  ('chimney-caps', 4, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/estate-roofline-with-two-stucco-chimneys-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/estate-roofline-with-two-stucco-chimneys-640.webp', 'Exterior · Whole home', 'Both chimneys capped in one visit', 'Every flue covered', 'Estate roofline with two capped stucco chimneys'),
  ('chimney-caps', 5, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/custom-brown-hip-cap-on-red-brick-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/custom-brown-hip-cap-on-red-brick-640.webp', 'Exterior · Custom cap', 'Custom hip cap on a brick stack', 'Screened against debris', 'Custom brown hip cap with mesh screen on a red brick chimney'),
  ('fireplace-inspection', 1, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-640.webp', 'Interior · Gas logs', 'Gas log set running at full flame', 'Even, steady burn', 'Gas log set burning in a herringbone firebox'),
  ('fireplace-inspection', 2, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-640.webp', 'Interior · Firebox', 'Firebox cleaned up and burner replaced', 'Burning clean again', 'Masonry firebox before and after a new gas burner was fitted'),
  ('fireplace-inspection', 3, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-log-set-installation-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-log-set-installation-before-after-640.webp', 'Interior · Gas logs', 'Old burner out, new log set in', 'Lights first time', 'Gas log set installation, before and after'),
  ('fireplace-inspection', 4, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-breast-resurfaced-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-breast-resurfaced-before-after-640.webp', 'Interior · Chimney breast', 'Chimney breast resurfaced', 'Whole wall renewed', 'Stone chimney breast before and after being resurfaced'),
  ('fireplace-inspection', 5, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-640.webp', 'Interior · Full system', 'Back in service for the season', 'Safe to use nightly', 'Painted brick fireplace lit in the evening'),
  ('fireplace-cleaning', 1, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-640.webp', 'Interior · Firebox', 'Years of soot cleared out', 'Like new again', 'Masonry firebox before and after a deep clean'),
  ('fireplace-cleaning', 2, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/plaster-fireplace-blue-fire-glass-920.webp', null, 'Interior · Fire glass', 'Fire glass washed and relaid', 'Sparkling again', 'Blue fire glass burning in a white plaster fireplace'),
  ('fireplace-cleaning', 3, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-in-black-painted-firebox-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-in-black-painted-firebox-640.webp', 'Interior · Log set', 'Logs lifted, firebox vacuumed out', 'No dust indoors', 'Clean gas log set in a black painted firebox'),
  ('fireplace-cleaning', 4, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-640.webp', 'Interior · Gas logs', 'Media rinsed and logs reset', 'Even, steady burn', 'Gas log set burning in a herringbone firebox'),
  ('fireplace-cleaning', 5, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-640.webp', 'Interior · Full system', 'Left clean and ready to light', 'Safe to use nightly', 'Painted brick fireplace lit in the evening'),
  ('fireplace-repair', 1, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-640.webp', 'Interior · Firebox', 'Firebox repaired and burner replaced', 'Burning clean again', 'Masonry firebox before and after a new gas burner was fitted'),
  ('fireplace-repair', 2, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-breast-resurfaced-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-breast-resurfaced-before-after-640.webp', 'Interior · Chimney breast', 'Chimney breast rebuilt and resurfaced', 'Whole wall renewed', 'Stone chimney breast before and after being resurfaced'),
  ('fireplace-repair', 3, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-log-set-installation-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-log-set-installation-before-after-640.webp', 'Interior · Gas logs', 'Failed burner stripped and replaced', 'Lights first time', 'Gas log set replacement, before and after'),
  ('fireplace-repair', 4, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-640.webp', 'Interior · Gas logs', 'Log set rebuilt and re-lit', 'Even, steady burn', 'Gas log set burning in a herringbone firebox'),
  ('fireplace-repair', 5, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-640.webp', 'Interior · Full system', 'Back in service the same week', 'Safe to use nightly', 'Painted brick fireplace lit in the evening'),
  ('fireplace-maintenance', 1, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-640.webp', 'Interior · Gas logs', 'Log set serviced and test-fired', 'Even, steady burn', 'Gas log set burning in a herringbone firebox'),
  ('fireplace-maintenance', 2, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-640.webp', 'Interior · Firebox', 'Firebox cleaned and burner serviced', 'Burning clean again', 'Masonry firebox before and after servicing'),
  ('fireplace-maintenance', 3, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-log-set-installation-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-log-set-installation-before-after-640.webp', 'Interior · Gas logs', 'Worn burner replaced before it failed', 'Lights first time', 'Gas log set replacement, before and after'),
  ('fireplace-maintenance', 4, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-breast-resurfaced-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-breast-resurfaced-before-after-640.webp', 'Interior · Chimney breast', 'Surround refinished and sealed', 'Whole wall renewed', 'Stone chimney breast before and after being resurfaced'),
  ('fireplace-maintenance', 5, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-640.webp', 'Interior · Full system', 'Ready before the first cold night', 'Safe to use nightly', 'Painted brick fireplace lit in the evening'),
  ('gas-fireplace-repair', 1, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-logs-burning-herringbone-firebox-640.webp', 'Interior · Gas logs', 'Flame back to full height', 'Even, steady burn', 'Gas log set burning in a herringbone firebox'),
  ('gas-fireplace-repair', 2, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/masonry-firebox-gas-burner-before-after-640.webp', 'Interior · Burner', 'New burner fitted in a tired firebox', 'Burning clean again', 'Masonry firebox before and after a new gas burner was fitted'),
  ('gas-fireplace-repair', 3, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-log-set-installation-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/gas-log-set-installation-before-after-640.webp', 'Interior · Gas logs', 'Old burner out, new log set in', 'Lights first time', 'Gas log set installation, before and after'),
  ('gas-fireplace-repair', 4, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-breast-resurfaced-before-after-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/chimney-breast-resurfaced-before-after-640.webp', 'Interior · Chimney breast', 'Firebox rebuilt behind a new surround', 'Whole wall renewed', 'Stone chimney breast before and after being resurfaced'),
  ('gas-fireplace-repair', 5, 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-920.webp', 'https://labekmkkpbgrxfpcsyvz.supabase.co/storage/v1/object/public/landing-v2/gallery/painted-brick-fireplace-evening-fire-640.webp', 'Interior · Full system', 'Relit and leak-tested', 'Safe to use nightly', 'Painted brick fireplace lit in the evening')
) as v(slug, sort_order, image_url, image_url_small, scope, title, result, alt)
join public.services s on s.slug = v.slug and s.brand = 'Premium Chimneys'
on conflict (service_id, sort_order) do nothing;
